Repository wecode-bootcamp-korea/32-1st-LuBean-frontend, pull requests merged in 2022-05, with the labels that each got.

#7 [32기 양재원] Footer 구독하기 버튼 이벤트 추가 및 세부 레이아웃 수정
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#6 [ 32기 최승이 ] nav 구현
  public/images/logo.svg
  public/images/logo_color.svg
  src/Router.js
  src/components/Nav/BtnWrap/BtnWrap.js
  src/components/Nav/Category/Category.js
  src/components/Nav/Category/Category.scss
  src/components/Nav/DropMenu/DropMenu.js
  src/components/Nav/DropMenu/DropMenu.scss
  src/components/Nav/MainMenu/MainMenu.js
  src/components/Nav/MainMenu/MainMenu.scss
  src/components/Nav/NAV_DATA.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/List/ProductsList/useFetch.js
Labels: Status: 수정 요청

#4 [32기 이현정]Feature/detail 상세페이지 구현
  public/data/detail.json
  public/images/products/coffee.png
  public/images/products/detail/main/detailmain.png
  public/images/products/detail/mainimg/beanimg01.png
  public/images/products/detail/mainimg/beanimg02.png
  public/images/products/detail/mainimg/beanimg03.png
  public/images/products/detail/mainimg/beanimg04.png
  public/images/products/detail/mainimg/beanimg05.png
  public/images/products/detail/mainimg/beanimg06.png
  public/images/products/detail/note/almond.png
  public/images/products/detail/note/apple.png
  public/images/products/detail/note/berry.png
  public/images/products/detail/note/blackcurrant.png
  public/images/products/detail/note/blacktea.png
  public/images/products/detail/note/blueberry.png
  public/images/products/detail/note/cherry.png
  public/images/products/detail/note/darkchoco.png
  public/images/products/detail/note/grapefruit.png
  public/images/products/detail/note/honey.png
  public/images/products/detail/note/maple.png
  public/images/products/detail/note/walnut.png
  public/images/products/detail/note/whitechocolate.png
  src/pages/Detail/Delivery/Delivery.js
  src/pages/Detail/Delivery/Delivery.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/Info/Info.js
  src/pages/Detail/Info/Info.scss
  src/pages/Detail/Modal/Modal.js
  src/pages/Detail/Modal/Modal.scss
  src/pages/Detail/Review/Review.js
  src/pages/Detail/Review/Review.scss
  src/pages/Detail/ReviewList/ReviewList.js
  src/pages/Detail/ReviewList/ReviewList.scss
  src/pages/Detail/SellContainer/SellContainer.js
  src/pages/Detail/SellContainer/SellContainer.scss
  src/pages/Detail/Star/Star.js
  src/pages/Detail/Tab/Tab.js
  src/pages/Detail/Tab/Tab.scss
  src/utils/makeStar.js
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#2 [32기 양재원] Main 페이지 전체 레이아웃 및 기능 구현 완료
  public/images/products/coffee_pkg_1.jpeg
  public/images/products/coffee_pkg_2.jpeg
  public/images/slides/brandImg.jpg
  public/images/slides/coffee.png
  public/images/slides/grid1.mp4
  public/images/slides/grid2.jpg
  public/images/slides/grid3.jpg
  public/images/slides/grid4.jpg
  public/images/slides/main0.jpg
  public/images/slides/main1.jpg
  public/images/slides/main2.jpg
  public/images/slides/main3.jpg
  public/images/slides/main4.jpg
  public/images/slides/main_slide_1.jpg
  public/images/slides/main_slide_2.jpg
  public/images/slides/main_slide_3.jpg
  public/images/slides/main_slide_4.jpg
  public/images/slides/main_slide_5.jpg
  src/Router.js
  src/pages/Main/Buttons/Buttons.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainData.js
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#1 [32기 김귀아] Login/SignUp 추가기능 구현 완료
  package-lock.json
  package.json
  public/images/Signup/IdIcon.png
  public/images/Signup/PWIcon.png
  public/images/Signup/coffeeBlue.jpg
  public/images/Signup/coffeeTable.jpg
  public/images/Signup/gift.jpg
  public/images/Signup/welcomePhoto.jpg
  src/Router.js
  src/pages/Login/Component/InputBox.js
  src/pages/Login/Component/InputBox.scss
  src/pages/Login/Component/LOGIN_LIST.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginSingUp.scss
  src/pages/Signup/Component/Input.js
  src/pages/Signup/Component/Input.scss
  src/pages/Signup/Component/SELECT_ADDRESS.js
  src/pages/Signup/Component/SELECT_EMAIL.js
  src/pages/Signup/Component/SelectInput.js
  src/pages/Signup/Component/SelectInput.scss
  src/pages/Signup/SignUp.js
  src/pages/Signup/SignUp.scss
  src/pages/Signup/SignUpDone.js
  src/pages/Signup/SignUpDone.scss
  src/pages/Signup/SignUpIntro.js
  src/pages/Signup/SignUpIntro.scss
  src/styles/variables.scss
  yarn.lock
Labels: Status: 리뷰 요청

#3 [ 32기 최승이 ] LIST 페이지
  public/data/blendedData.json
  public/data/decaffeinData.json
  public/data/singleOriginData.json
  public/images/goods/top/coffeeGoods_bg.jpg
  public/images/goods/top/cup_bg.jpg
  public/images/goods/top/etc_bg.jpg
  public/images/products/thumbnail/blended/blended_beans.jpeg
  public/images/products/thumbnail/blended/blended_pkg.jpeg
  public/images/products/thumbnail/decaffein/decaffein_beans.jpeg
  public/images/products/thumbnail/decaffein/decaffein_pkg.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_brasil.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_colombia.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_costarica.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_elsalvador.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_ethiopia.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_guatemala.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_indonesia.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_kenya.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_nicaragua.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_panama.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_papuanewquinea.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_pkg.jpeg
  public/images/products/thumbnail/singleorigin/singleorigin_tanzania.jpeg
  public/images/products/top/blended_bg.jpg
  public/images/products/top/decaffeine_bg.jpg
  public/images/products/top/singleOrigin_bg.jpg
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/BtnWrap/BtnWrap.js
  src/components/Nav/MainMenu/MainMenu.js
  src/components/Nav/NAV_DATA.js
  src/components/Nav/Nav.js
  src/pages/Country/Country.js
  src/pages/Country/Country.scss
  src/pages/List/Info/Info.js
  src/pages/List/Info/Info.scss
  src/pages/List/List.js
  src/pages/List/List.scss
  src/pages/List/ListComponent.js
  src/pages/List/ProductsList/ProductsList.js
  src/pages/List/ProductsList/ProductsList.scss
  src/pages/List/ProductsList/useFetch.js
  src/pages/List/Tag/Tag.js
  src/pages/List/Tag/Tag.scss
Labels: Status: 수정 요청, Status: 추가 기능 구현중
